# Generated by Django 6.0.2 on 2026-02-26 15:04

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.SlugField(unique=True)),
                ('meta_title', models.CharField(max_length=300)),
                ('meta_description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='blog/thumbnails')),
                ('author', models.CharField(max_length=100)),
                ('author_image', models.ImageField(upload_to='blog/authors/')),
                ('content', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
